spring:
  application:
    name: mappingservice
  data:
    mongodb:
      uri: mongodb://localhost/mapping_service # Mongo database URI. When set, host and port are ignored.
      port: 27017 # Mongo server port.
      enabled: true # Enable Mongo repositories.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false