spring:
  application:
      name: mappingservice
  datasource:
    url: jdbc:postgresql://postgres:5432/mapping_db
    username: postgres
    password: postgres
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryservice:8761/eureka/
    fetch-registry: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5433/mapping_db
    username: postgres
    password: postgres
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
